package com.resmed.refresh.packets;

public enum VLPacketType
{
	PACKET_TYPE_APP_LOAD("PACKET_TYPE_APP_LOAD", 6),
	PACKET_TYPE_BIO_32("PACKET_TYPE_BIO_32", 2),
	PACKET_TYPE_BIO_64("PACKET_TYPE_BIO_64", 4),
	PACKET_TYPE_CALL("PACKET_TYPE_CALL", 0),
	PACKET_TYPE_COMPRESSED_DATA("PACKET_TYPE_COMPRESSED_DATA", 7),
	PACKET_TYPE_ENV_1("PACKET_TYPE_ENV_1", 3),
	PACKET_TYPE_ENV_60("PACKET_TYPE_ENV_60", 5),
	PACKET_TYPE_FW_LOAD_END("PACKET_TYPE_FW_LOAD_END", 21),
	PACKET_TYPE_MAX_VLP("PACKET_TYPE_MAX_VLP", 22),
	PACKET_TYPE_NOTE_BIO_1("PACKET_TYPE_NOTE_BIO_1", 18),
	PACKET_TYPE_NOTE_ENV_1("PACKET_TYPE_NOTE_ENV_1", 19),
	PACKET_TYPE_NOTE_FW_UPGRADE("PACKET_TYPE_NOTE_FW_UPGRADE", 20),
	PACKET_TYPE_NOTE_HEARTBEAT("PACKET_TYPE_NOTE_HEARTBEAT", 16),
	PACKET_TYPE_NOTE_ILLUMINANCE_CHANGE("PACKET_TYPE_NOTE_ILLUMINANCE_CHANGE", 17),
	PACKET_TYPE_NOTE_RESUME("PACKET_TYPE_NOTE_RESUME", 13),
	PACKET_TYPE_NOTE_RTC_UNAVAILABLE("PACKET_TYPE_NOTE_RTC_UNAVAILABLE", 12),
	PACKET_TYPE_NOTE_STOP_BROWNOUT("PACKET_TYPE_NOTE_STOP_BROWNOUT", 8),
	PACKET_TYPE_NOTE_STOP_RESET("PACKET_TYPE_NOTE_STOP_RESET", 10),
	PACKET_TYPE_NOTE_STOP_TIMEOUT("PACKET_TYPE_NOTE_STOP_TIMEOUT", 11),
	PACKET_TYPE_NOTE_STOP_WATCHDOG("PACKET_TYPE_NOTE_STOP_WATCHDOG", 9),
	PACKET_TYPE_NOTE_STORE_FOREIGN("PACKET_TYPE_NOTE_STORE_FOREIGN", 14),
	PACKET_TYPE_NOTE_STORE_LOCAL("PACKET_TYPE_NOTE_STORE_LOCAL", 15),
	PACKET_TYPE_RETURN("PACKET_TYPE_RETURN", 1);

	private VLPacketType(final String s, final int n) {
	}
}
