package com.resmed.refresh.packets;

public enum VLPacketType {
	PACKET_TYPE_CALL,
	PACKET_TYPE_RETURN,
	PACKET_TYPE_BIO_32,
	PACKET_TYPE_ENV_1,
	PACKET_TYPE_BIO_64,
	PACKET_TYPE_ENV_60,
	PACKET_TYPE_APP_LOAD,
	PACKET_TYPE_COMPRESSED_DATA,
	PACKET_TYPE_NOTE_STOP_BROWNOUT,
	PACKET_TYPE_NOTE_STOP_WATCHDOG,
	PACKET_TYPE_NOTE_STOP_RESET,
	PACKET_TYPE_NOTE_STOP_TIMEOUT,
	PACKET_TYPE_NOTE_RTC_UNAVAILABLE,
	PACKET_TYPE_NOTE_RESUME,
	PACKET_TYPE_NOTE_STORE_FOREIGN,
	PACKET_TYPE_NOTE_STORE_LOCAL,
	PACKET_TYPE_NOTE_HEARTBEAT,
	PACKET_TYPE_NOTE_ILLUMINANCE_CHANGE,
	PACKET_TYPE_NOTE_BIO_1,
	PACKET_TYPE_NOTE_ENV_1,
	PACKET_TYPE_NOTE_FW_UPGRADE,
	PACKET_TYPE_FW_LOAD_END,
	PACKET_TYPE_MAX_VLP
}