package com.resmed.refresh.model.mappers;

import com.resmed.refresh.model.RST_Settings;
import com.resmed.refresh.model.RST_User;
import com.resmed.refresh.model.RST_UserProfile;
import com.resmed.refresh.model.RefreshModelController;
import com.resmed.refresh.model.json.UserProfile;
import com.resmed.refresh.utils.RefreshTools;

public class UserProfileMapper
{
  public static UserProfile getProfile(RST_UserProfile paramRST_UserProfile)
  {
    UserProfile localUserProfile = new UserProfile();
    localUserProfile.setBedTime(paramRST_UserProfile.getBedTime());
    localUserProfile.setConsumeAlcohol(paramRST_UserProfile.getConsumeAlcohol());
    localUserProfile.setDateOfBirth(RefreshTools.getStringFromDate(paramRST_UserProfile.getDateOfBirth()));
    localUserProfile.setExerciseIntensity(paramRST_UserProfile.getExerciseIntensity());
    localUserProfile.setExerciseBeforeBed(paramRST_UserProfile.getExerciseBeforeBed());
    localUserProfile.setGender(paramRST_UserProfile.getNewGender());
    localUserProfile.setHasPet(paramRST_UserProfile.getHasPet());
    localUserProfile.setHasPetInBed(paramRST_UserProfile.getHasPetInBed());
    localUserProfile.setHasSleepPartner(paramRST_UserProfile.getHasSleepPartner());
    localUserProfile.setHeight(paramRST_UserProfile.getHeight());
    localUserProfile.setHighBloodPressure(paramRST_UserProfile.getHighBloodPressure());
    localUserProfile.setIllnessForSleep(paramRST_UserProfile.getIllnessForSleep());
    localUserProfile.setMedication(paramRST_UserProfile.getMedication());
    localUserProfile.setMedicationFrequency(paramRST_UserProfile.getMedicationFrequency());
    localUserProfile.setNaps(paramRST_UserProfile.getNaps());
    localUserProfile.setNeckSize(paramRST_UserProfile.getNeckSize());
    localUserProfile.setNumCaffeineDrinks(paramRST_UserProfile.getNumCaffeineDrinks());
    localUserProfile.setNumCigarettes(paramRST_UserProfile.getNumCigarettes());
    localUserProfile.setNumDrinks(paramRST_UserProfile.getNumDrinks());
    localUserProfile.setNumExercises(paramRST_UserProfile.getNumExercises());
    localUserProfile.setSleepMover(paramRST_UserProfile.getSleepMover());
    localUserProfile.setSleepProblems(paramRST_UserProfile.getSleepProblems());
    localUserProfile.setSmoker(paramRST_UserProfile.getSmoker());
    localUserProfile.setSnorer(paramRST_UserProfile.getSnorer());
    localUserProfile.setStopsBreathing(paramRST_UserProfile.getStopsBreathing());
    localUserProfile.setStressedFrequency(paramRST_UserProfile.getStressedFrequency());
    localUserProfile.setTiredDaytime(paramRST_UserProfile.getTiredDaytime());
    localUserProfile.setWeight(paramRST_UserProfile.getWeight());
    localUserProfile.setHeightUnit(paramRST_UserProfile.getHeightUnit());
    localUserProfile.setWeightUnit(paramRST_UserProfile.getWeightUnit());
    localUserProfile.setTemperatureUnit(paramRST_UserProfile.getTemperatureUnit());
    localUserProfile.setLocale(paramRST_UserProfile.getLocale());
    localUserProfile.setCountryCode(paramRST_UserProfile.getCountryCode());
    localUserProfile.setPrescriptionPillsType(paramRST_UserProfile.getPrescriptionPillsType());
    localUserProfile.setPrescriptionPillsConcern(paramRST_UserProfile.getPrescriptionPillsConcern());
    localUserProfile.setOTCMedicationType(paramRST_UserProfile.getOTCMedicationType());
    localUserProfile.setOTCMedicationFrequency(paramRST_UserProfile.getOTCMedicationFrequency());
    localUserProfile.setOTCMedicationConcern(paramRST_UserProfile.getOTCMedicationConcern());
    localUserProfile.setHerbalRemediesType(paramRST_UserProfile.getHerbalRemediesType());
    localUserProfile.setHerbalRemediesFrequency(paramRST_UserProfile.getHerbalRemediesFrequency());
    localUserProfile.setControlBedroomTemperature(paramRST_UserProfile.getControlBedroomTemperature());
    localUserProfile.setHumidifierUsed(paramRST_UserProfile.isHumidifierUsed());
    localUserProfile.setAirPurifierUsed(paramRST_UserProfile.isAirPurifierUsed());
    localUserProfile.setNoiseLevelInBedroom(paramRST_UserProfile.getNoiseLevelInBedroom());
    localUserProfile.setHowOftenElectronicsUsed(paramRST_UserProfile.getHowOftenElectronicsUsed());
    localUserProfile.setGetWokenUpInNightByAny(paramRST_UserProfile.getGetWokenUpInNightByAny());
    localUserProfile.setSoundUsedInSleep(paramRST_UserProfile.isSoundUsedInSleep());
    localUserProfile.setTypeOfSoundUsedInSleep(paramRST_UserProfile.getTypeOfSoundUsedInSleep());
    localUserProfile.setLevelOfLightInBedroom(paramRST_UserProfile.getLevelOfLightInBedroom());
    localUserProfile.setReduceAmountOfLightInBedroom(paramRST_UserProfile.getReduceAmountOfLightInBedroom());
    localUserProfile.setSourceOfLightInBedroom(paramRST_UserProfile.getSourceOfLightInBedroom());
    localUserProfile.setSpecialLightUsedInSleep(paramRST_UserProfile.getSpecialLightUsedInSleep());
    localUserProfile.setMattressType(paramRST_UserProfile.getMattressType());
    localUserProfile.setMattressSize(paramRST_UserProfile.getMattressSize());
    localUserProfile.setMattressBrand(paramRST_UserProfile.getMattressBrand());
    localUserProfile.setMattressAge(paramRST_UserProfile.getMattressAge());
    localUserProfile.setMattressPadTopperOnBed(paramRST_UserProfile.isMattressPadTopperOnBed());
    localUserProfile.setPillowsType(paramRST_UserProfile.getPillowsType());
    localUserProfile.setPillowsAge(paramRST_UserProfile.getPillowsAge());
    localUserProfile.setSleepingPosition(paramRST_UserProfile.getSleepingPosition());
    localUserProfile.setWakeUpDifficulties(paramRST_UserProfile.getWakeUpDifficulties());
    localUserProfile.setMorningAlertness(paramRST_UserProfile.getMorningAlertness());
    localUserProfile.setTypeofPerson(paramRST_UserProfile.getTypeofPerson());
    localUserProfile.setTravelImpact(paramRST_UserProfile.getTravelImpact());
    localUserProfile.setChildrenCount(paramRST_UserProfile.getChildrenCount());
    localUserProfile.setNapTime(paramRST_UserProfile.getNapTime());
    localUserProfile.setSleepDisorder(paramRST_UserProfile.getSleepDisorder());
    localUserProfile.setSleepDisorderMachine(paramRST_UserProfile.getSleepDisorderMachine());
    localUserProfile.setMachineManufacturer(paramRST_UserProfile.getMachineManufacturer());
    localUserProfile.setAffectsYourSleep(paramRST_UserProfile.getAffectsYourSleep());
    localUserProfile.setStayingAwakeDuringDay(paramRST_UserProfile.isStayingAwakeDuringDay());
    localUserProfile.setConcernsOnSleepProblem(paramRST_UserProfile.getConcernsOnSleepProblem());
    localUserProfile.setExtentInterfereSleepProblem(paramRST_UserProfile.getExtentInterfereSleepProblem());
    localUserProfile.setSleepingPositionSnore(paramRST_UserProfile.getSleepingPositionSnore());
    localUserProfile.setDryMouth(paramRST_UserProfile.isDryMouth());
    localUserProfile.setNasalCongestion(paramRST_UserProfile.isNasalCongestion());
    localUserProfile.setCrawlingSensation(paramRST_UserProfile.isCrawlingSensation());
    localUserProfile.setMuscleTension(paramRST_UserProfile.isMuscleTension());
    localUserProfile.setLegsStillAtNight(paramRST_UserProfile.isLegsStillAtNight());
    localUserProfile.setSufferFromAllergies(paramRST_UserProfile.isSufferFromAllergies());
    localUserProfile.setBreathingObstruction(paramRST_UserProfile.isBreathingObstruction());
    localUserProfile.setSnoreFrequency(paramRST_UserProfile.getSnoreFrequency());
    localUserProfile.setSleepWithPartner(paramRST_UserProfile.isSleepWithPartner());
    localUserProfile.setPetSleepWithYouOnBed(paramRST_UserProfile.getPetSleepWithYouOnBed());
    localUserProfile.setUsingSleepAids(paramRST_UserProfile.getUsingSleepAids());
    localUserProfile.setPrescriptionPillsFrequency(paramRST_UserProfile.getPrescriptionPillsFrequency());
    localUserProfile.setOtherMachineManufacturer(paramRST_UserProfile.getOtherMachineManufacturer());
    localUserProfile.setOtherPrescriptionPillsType(paramRST_UserProfile.getOtherPrescriptionPillsType());
    localUserProfile.setOtherHerbalRemediesType(paramRST_UserProfile.getOtherHerbalRemediesType());
    localUserProfile.setOtherMattressType(paramRST_UserProfile.getOtherMattressType());
    localUserProfile.setOtherMattressBrand(paramRST_UserProfile.getOtherMattressBrand());
    localUserProfile.setOtherPillowsType(paramRST_UserProfile.getOtherPillowsType());
    localUserProfile.setOtherControlBedroomTemperature(paramRST_UserProfile.getOtherControlBedroomTemperature());
    localUserProfile.setOtherTypeOfSoundUsedInSleep(paramRST_UserProfile.getOtherTypeOfSoundUsedInSleep());
    localUserProfile.setOtherSourceOfLightInBedroom(paramRST_UserProfile.getOtherSourceOfLightInBedroom());
    localUserProfile.setOtherReduceAmountOfLightInBedroom(paramRST_UserProfile.getOtherReduceAmountOfLightInBedroom());
    return localUserProfile;
  }
  
  private static RST_UserProfile getRST_UserProfile(UserProfile paramUserProfile)
  {
    RST_UserProfile localRST_UserProfile = RefreshModelController.getInstance().getUser().getProfile();
    localRST_UserProfile.setBedTime(paramUserProfile.getBedTime());
    localRST_UserProfile.setConsumeAlcohol(paramUserProfile.getConsumeAlcohol());
    localRST_UserProfile.setDateOfBirth(RefreshTools.getDateFromString(paramUserProfile.getDateOfBirth()));
    localRST_UserProfile.setExerciseBeforeBed(paramUserProfile.getExerciseBeforeBed());
    localRST_UserProfile.setExerciseIntensity(paramUserProfile.getExerciseIntensity());
    localRST_UserProfile.setNewGender(paramUserProfile.getGender());
    localRST_UserProfile.setHasPet(paramUserProfile.getHasPet());
    localRST_UserProfile.setHasPetInBed(paramUserProfile.getHasPetInBed());
    localRST_UserProfile.setHasSleepPartner(paramUserProfile.getHasSleepPartner());
    localRST_UserProfile.setHeight(paramUserProfile.getHeight());
    localRST_UserProfile.setHighBloodPressure(paramUserProfile.getHighBloodPressure());
    localRST_UserProfile.setIllnessForSleep(paramUserProfile.getIllnessForSleep());
    localRST_UserProfile.setMedication(paramUserProfile.getMedication());
    localRST_UserProfile.setMedicationFrequency(paramUserProfile.getMedicationFrequency());
    localRST_UserProfile.setNaps(paramUserProfile.getNaps());
    localRST_UserProfile.setNeckSize(paramUserProfile.getNeckSize());
    localRST_UserProfile.setNumCaffeineDrinks(paramUserProfile.getNumCaffeineDrinks());
    localRST_UserProfile.setNumCigarettes(paramUserProfile.getNumCigarettes());
    localRST_UserProfile.setNumDrinks(paramUserProfile.getNumDrinks());
    localRST_UserProfile.setNumExercises(paramUserProfile.getNumExercises());
    localRST_UserProfile.setSleepMover(paramUserProfile.getSleepMover());
    localRST_UserProfile.setSleepProblems(paramUserProfile.getSleepProblems());
    localRST_UserProfile.setSmoker(paramUserProfile.getSmoker());
    localRST_UserProfile.setSnorer(paramUserProfile.getSnorer());
    localRST_UserProfile.setStopsBreathing(paramUserProfile.getStopsBreathing());
    localRST_UserProfile.setStressedFrequency(paramUserProfile.getStressedFrequency());
    localRST_UserProfile.setTiredDaytime(paramUserProfile.getTiredDaytime());
    localRST_UserProfile.setWeight(paramUserProfile.getWeight());
    localRST_UserProfile.setHeightUnit(paramUserProfile.getHeightUnit());
    localRST_UserProfile.setWeightUnit(paramUserProfile.getWeightUnit());
    localRST_UserProfile.setTemperatureUnit(paramUserProfile.getTemperatureUnit());
    localRST_UserProfile.setLocale(paramUserProfile.getLocale());
    localRST_UserProfile.setCountryCode(paramUserProfile.getCountryCode());
    localRST_UserProfile.setPrescriptionPillsType(paramUserProfile.getPrescriptionPillsType());
    localRST_UserProfile.setPrescriptionPillsConcern(paramUserProfile.getPrescriptionPillsConcern());
    localRST_UserProfile.setOTCMedicationType(paramUserProfile.getOTCMedicationType());
    localRST_UserProfile.setOTCMedicationFrequency(paramUserProfile.getOTCMedicationFrequency());
    localRST_UserProfile.setOTCMedicationConcern(paramUserProfile.getOTCMedicationConcern());
    localRST_UserProfile.setHerbalRemediesType(paramUserProfile.getHerbalRemediesType());
    localRST_UserProfile.setHerbalRemediesFrequency(paramUserProfile.getHerbalRemediesFrequency());
    localRST_UserProfile.setControlBedroomTemperature(paramUserProfile.getControlBedroomTemperature());
    localRST_UserProfile.setHumidifierUsed(paramUserProfile.isHumidifierUsed());
    localRST_UserProfile.setAirPurifierUsed(paramUserProfile.isAirPurifierUsed());
    localRST_UserProfile.setNoiseLevelInBedroom(paramUserProfile.getNoiseLevelInBedroom());
    localRST_UserProfile.setHowOftenElectronicsUsed(paramUserProfile.getHowOftenElectronicsUsed());
    localRST_UserProfile.setGetWokenUpInNightByAny(paramUserProfile.getGetWokenUpInNightByAny());
    localRST_UserProfile.setSoundUsedInSleep(paramUserProfile.isSoundUsedInSleep());
    localRST_UserProfile.setTypeOfSoundUsedInSleep(paramUserProfile.getTypeOfSoundUsedInSleep());
    localRST_UserProfile.setLevelOfLightInBedroom(paramUserProfile.getLevelOfLightInBedroom());
    localRST_UserProfile.setReduceAmountOfLightInBedroom(paramUserProfile.getReduceAmountOfLightInBedroom());
    localRST_UserProfile.setSourceOfLightInBedroom(paramUserProfile.getSourceOfLightInBedroom());
    localRST_UserProfile.setSpecialLightUsedInSleep(paramUserProfile.getSpecialLightUsedInSleep());
    localRST_UserProfile.setMattressType(paramUserProfile.getMattressType());
    localRST_UserProfile.setMattressSize(paramUserProfile.getMattressSize());
    localRST_UserProfile.setMattressBrand(paramUserProfile.getMattressBrand());
    localRST_UserProfile.setMattressAge(paramUserProfile.getMattressAge());
    localRST_UserProfile.setMattressPadTopperOnBed(paramUserProfile.isMattressPadTopperOnBed());
    localRST_UserProfile.setPillowsType(paramUserProfile.getPillowsType());
    localRST_UserProfile.setPillowsAge(paramUserProfile.getPillowsAge());
    localRST_UserProfile.setSleepingPosition(paramUserProfile.getSleepingPosition());
    localRST_UserProfile.setWakeUpDifficulties(paramUserProfile.getWakeUpDifficulties());
    localRST_UserProfile.setMorningAlertness(paramUserProfile.getMorningAlertness());
    localRST_UserProfile.setTypeofPerson(paramUserProfile.getTypeofPerson());
    localRST_UserProfile.setTravelImpact(paramUserProfile.getTravelImpact());
    localRST_UserProfile.setChildrenCount(paramUserProfile.getChildrenCount());
    localRST_UserProfile.setNapTime(paramUserProfile.getNapTime());
    localRST_UserProfile.setSleepDisorder(paramUserProfile.getSleepDisorder());
    localRST_UserProfile.setSleepDisorderMachine(paramUserProfile.getSleepDisorderMachine());
    localRST_UserProfile.setMachineManufacturer(paramUserProfile.getMachineManufacturer());
    localRST_UserProfile.setAffectsYourSleep(paramUserProfile.getAffectsYourSleep());
    localRST_UserProfile.setStayingAwakeDuringDay(paramUserProfile.isStayingAwakeDuringDay());
    localRST_UserProfile.setConcernsOnSleepProblem(paramUserProfile.getConcernsOnSleepProblem());
    localRST_UserProfile.setExtentInterfereSleepProblem(paramUserProfile.getExtentInterfereSleepProblem());
    localRST_UserProfile.setSleepingPositionSnore(paramUserProfile.getSleepingPositionSnore());
    localRST_UserProfile.setDryMouth(paramUserProfile.isDryMouth());
    localRST_UserProfile.setNasalCongestion(paramUserProfile.isNasalCongestion());
    localRST_UserProfile.setCrawlingSensation(paramUserProfile.isCrawlingSensation());
    localRST_UserProfile.setMuscleTension(paramUserProfile.isMuscleTension());
    localRST_UserProfile.setLegsStillAtNight(paramUserProfile.isLegsStillAtNight());
    localRST_UserProfile.setSufferFromAllergies(paramUserProfile.isSufferFromAllergies());
    localRST_UserProfile.setBreathingObstruction(paramUserProfile.isBreathingObstruction());
    localRST_UserProfile.setSnoreFrequency(paramUserProfile.getSnoreFrequency());
    localRST_UserProfile.setSleepWithPartner(paramUserProfile.isSleepWithPartner());
    localRST_UserProfile.setPetSleepWithYouOnBed(paramUserProfile.getPetSleepWithYouOnBed());
    localRST_UserProfile.setUsingSleepAids(paramUserProfile.getUsingSleepAids());
    localRST_UserProfile.setPrescriptionPillsFrequency(paramUserProfile.getPrescriptionPillsFrequency());
    localRST_UserProfile.setOtherMachineManufacturer(paramUserProfile.getOtherMachineManufacturer());
    localRST_UserProfile.setOtherPrescriptionPillsType(paramUserProfile.getOtherPrescriptionPillsType());
    localRST_UserProfile.setOtherHerbalRemediesType(paramUserProfile.getOtherHerbalRemediesType());
    localRST_UserProfile.setOtherMattressType(paramUserProfile.getOtherMattressType());
    localRST_UserProfile.setOtherMattressBrand(paramUserProfile.getOtherMattressBrand());
    localRST_UserProfile.setOtherPillowsType(paramUserProfile.getOtherPillowsType());
    localRST_UserProfile.setOtherControlBedroomTemperature(paramUserProfile.getOtherControlBedroomTemperature());
    localRST_UserProfile.setOtherTypeOfSoundUsedInSleep(paramUserProfile.getOtherTypeOfSoundUsedInSleep());
    localRST_UserProfile.setOtherSourceOfLightInBedroom(paramUserProfile.getOtherSourceOfLightInBedroom());
    localRST_UserProfile.setOtherReduceAmountOfLightInBedroom(paramUserProfile.getOtherReduceAmountOfLightInBedroom());
    return localRST_UserProfile;
  }
  
  public static RST_UserProfile processUserProfile(UserProfile paramUserProfile)
  {
    RefreshModelController localRefreshModelController = RefreshModelController.getInstance();
    Object localObject = localRefreshModelController.getUser();
    RST_UserProfile localRST_UserProfile = getRST_UserProfile(paramUserProfile);
    ((RST_User)localObject).setAndSaveProfile(localRST_UserProfile);
    ((RST_User)localObject).getLocation().setTimezone(paramUserProfile.getTimeZone());
    localObject = ((RST_User)localObject).getSettings();
    ((RST_Settings)localObject).setLocationPermission(paramUserProfile.getLocationPermission());
    ((RST_Settings)localObject).setPushNotifications(paramUserProfile.getPushNotifications());
    ((RST_Settings)localObject).setUseMetricUnits(paramUserProfile.getUseMetricUnits());
    ((RST_Settings)localObject).setTac1(paramUserProfile.getTac1());
    ((RST_Settings)localObject).setTac2(paramUserProfile.getTac2());
    ((RST_Settings)localObject).setTac3(paramUserProfile.getTac3());
    ((RST_Settings)localObject).setHeightUnit(paramUserProfile.getHeightUnit());
    ((RST_Settings)localObject).setWeightUnit(paramUserProfile.getWeightUnit());
    ((RST_Settings)localObject).setTemperatureUnit(paramUserProfile.getTemperatureUnit());
    ((RST_Settings)localObject).setLocale(paramUserProfile.getLocale());
    ((RST_Settings)localObject).setCountryCode(paramUserProfile.getCountryCode());
    localRefreshModelController.save();
    return localRST_UserProfile;
  }
}


/* Location:              C:\Root\@Objects\Tablet\Resmed\App Inspect\JD Gui\com.resmed.refresh-158.jar!\com\resmed\refresh\model\mappers\UserProfileMapper.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       0.7.1
 */