package com.resmed.refresh.bluetooth;

public enum CONNECTION_STATE {
	BLUETOOTH_OFF("BLUETOOTH_OFF", 3),
	BLUETOOTH_ON("BLUETOOTH_ON", 2),

	SOCKET_NOT_CONNECTED("SOCKET_NOT_CONNECTED", 6),
	SOCKET_BROKEN("SOCKET_BROKEN", 4),
	SOCKET_RECONNECTING("SOCKET_RECONNECTING", 5),
	SOCKET_CONNECTED("SOCKET_CONNECTED", 7),

	SESSION_OPENING("SESSION_OPENING", 8),
	SESSION_OPENED("SESSION_OPENED", 9),

	REAL_STREAM_OFF("REAL_STREAM_OFF", 0),
	REAL_STREAM_ON("REAL_STREAM_ON", 10),
	NIGHT_TRACK_OFF("NIGHT_TRACK_OFF", 1),
	NIGHT_TRACK_ON("NIGHT_TRACK_ON", 11);

	public String name;
	public int value;
	CONNECTION_STATE(final String name, final int value) {
		this.name = name;
		this.value = value;
	}
}